name: Merge CI
on: [pull-request]
jobs:
 Explore-GitHub-Actions:
   runs-on: [windows-latest, ubuntu latest, macos-latest]
   steps:
     - uses: actions/checkout@v2
     - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
     - run: python main.py